---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Create database user with name 'nagiostest' and password 'nagiostest' with all database privileges
- mysql_user:
    name: nagiostest
    password: nagiostest
    priv: '*.*:PROCESS'
    state: present
  ignore_errors: yes
