---
# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Create database user with name 'nagiostest' and password 'nagiostest' with all database privileges
- mysql_user:
    name: nagiostest
    password: nagiostest
    priv: '*.*:PROCESS'
    state: present
  ignore_errors: yes
