# Variable configuration.
- include_vars: Debian.yml

- name: Install common software requirements nagios
  ignore_errors: yes
  apt:
    pkg:
      - nagios-nrpe-server
      - nagios-plugins
        #- python2-pip
      - python-pip
    state: present
    install_recommends: no
    update_cache: yes
  when: ansible_distribution_major_version == '14' or ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' or  ansible_distribution_major_version == '9' or ansible_distribution_major_version == "10"


- name: Install common software requirements nagios python3
  ignore_errors: yes
  apt:
    pkg:
      - nagios-nrpe-server
      - nagios-plugins
      - python3-pip
    state: present
    install_recommends: no
    update_cache: yes
  when: ansible_distribution_major_version == '20' or ansible_distribution_major_version == '18' or ansible_distribution_major_version == '16'

- name: Installing pymysql for dependency
  ignore_errors: yes
  pip:
    name: pymysql
    state: present

- name: Configuration nrpe
  template:
    src: "hoster.j2"
    dest: "/etc/nagios/nrpe.d/hoster.cfg"
  notify: restart nrpe
