# Variable configuration.
- include_vars: Debian.yml

- name: Install common software requirements nagios
  ignore_errors: yes
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
    update_cache: yes
  with_items: "{{ packages }}"

- name: Installing pip_modules for dependency
  ignore_errors: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_modules }}"  

- name: Configuration nrpe
  template:
    src: "hoster.j2"
    dest: "/etc/nagios/nrpe.d/hoster.cfg"
  notify: restart nrpe
