- name: Start install
  hosts: Administration
  become: yes
  
  roles:
    - role: zabbix
      Hostname: "{{ ansible_hostname }}"  #example: hoster.by | default hostname  
      HostMetadata: test_hoster           #example: admin_hoster
    - role: puppet
    - role: nagios
    - role: rdiff-backup
