- name: Install common software requirements rdiff-backup
  yum:
    name:
      - librsync-devel
      - python-devel
      - gcc
    state: present

- name: Copy archive rdiff-backup
  copy:
    src: rdiff-backup-1.3.3.tar.gz
    dest: /opt/

- name: Unarchive a file on the remote machine
  unarchive:
    src: /opt/rdiff-backup-1.3.3.tar.gz
    dest: /opt/
    remote_src: yes   
    
- name: Install rdiff-backup
  command: "python setup.py install --prefix=/usr"
  args:
    chdir: /opt/rdiff-backup-1.3.3

