---
# Setup/install tasks.
- include_tasks: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'


  
