- name: Adding Zabbix repository rhel_8
  command: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm 
  ignore_errors: yes
  when: ansible_distribution_major_version == '8'

- name: Adding Zabbix repository rhel_7
  command: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
  ignore_errors: yes
  when: ansible_distribution_major_version == '7'
  
- name: Adding Zabbix repository rhel_6
  command: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/6/x86_64/zabbix-release-5.0-1.el6.noarch.rpm
  ignore_errors: yes
  when: ansible_distribution_major_version == '6'

- name: Install zabbix-agent
  yum:
    name: zabbix-agent
    state: latest 
    update_cache: yes
  notify: start zabbix-agent

- name: Configuration zabbix-agent
  template:
    src: "zabbix_agentd.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
  notify: restart zabbix-agent

